spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: maestra
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

server:
  port: 8083

logging:
  level:
    org.springframework.r2dbc: INFO
